###############
## Animation ##
###############

animation = workspaces, 1, 5, default, slide
animation = windows, 1, 1.5, default

windowrule = animation slide top, clipse
layerrule = animation slide top, wofi

