general {
  col.active_border = rgb(7DAEA3)
  col.inactive_border = rgb(2E3B3B)
}

group {
  col.border_active = rgb(A9B665)
  col.border_inactive = rgb(333E34)
  col.border_locked_active = rgb(EA6962)
  col.border_locked_inactive = rgb(442E2D)

  groupbar {
    col.active = rgb(A9B665)
    col.inactive = rgb(333E34)
    col.locked_active = rgb(EA6962)
    col.locked_inactive = rgb(442E2D)
  }
}
