# Black
color0 #665c54
color8 #928374

# Red
color1 #DF5B61
color9 #DF5B61

# Green
color2  #78B892
color10 #78B892

# Yellow
color3  #E89982
color11 #ecd28b

# Blue
color4  #6791C9
color12 #6791C9

# Magenta
color5  #c58cec
color13 #c58cec

# Cyan
color6  #67AFC1
color14 #67AFC1

# White
color7  #edeff0
color15 #edeff0

background #0c0e0f
foreground #edeff0

selection_background #27292a
selection_foreground #edeff0

cursor #edeff0
cursor_text_color background

active_tab_font_style bold
active_tab_foreground   #6791C9
active_tab_background   #27292a
inactive_tab_foreground #edeff0
inactive_tab_background #161819

active_border_color #6791C9
inactive_border_color #505253
