abbr nv 'nvim'
abbr nvc 'nvim --clean'
abbr lg 'lazygit'
abbr ga 'git add'
abbr gc 'git commit -m'
abbr gp 'git push'
abbr gpl 'git pull'
abbr gs 'git status'
abbr dx 'distrobox'
abbr dxe 'distrobox enter -n'
abbr dxs 'distrobox stop'
