color0 #43474c
color1 #ffb4ab
color2 #b5c8e3
color3 #c0c7d2
color4 #dcbddb
color5 #b5c8e3
color6 #c0c7d2
color7 #e4e2e4
color8 #8e9197
color9 #ffb4ab
color10 #b5c8e3
color11 #c0c7d2
color12 #dcbddb
color13 #b5c8e3
color14 #c0c7d2
color15 #e4e2e4

cursor                #e4e2e4
cursor_text_color     #131315
background            #131315
foreground            #e4e2e4
selection_foreground  #c4c6cd
selection_background  #43474c
active_border_color   #b5c8e3
inactive_border_color #43474c
url_color             #b5c8e3

active_tab_foreground   #1f3246
active_tab_background   #b5c8e3
inactive_tab_foreground #c4c6cd
inactive_tab_background #43474c
cursor_trail_color      #c4c6cd
