#!/bin/bash

entries="Game Mode\nZoom\nFull Screenshot\nRestart Hyprpanel\nLock Screen\nClear Notification\nTyping Test"

selected=$(echo -e "$entries" | (pidof fuzzel || fuzzel --dmenu --cache /dev/null) | awk '{gsub(/ /, ""); print tolower($0)}')

case $selected in
gamemode)
  /bin/bash ~/.config/hypr/scripts/hypr_action gamemode
  ;;
zoom)
  hypr-zoom -duration=600 -steps=150 -easing=OutBack -easingOut=InBack -interp=Linear -target=2.8
  ;;
fullscreenshot)
  /bin/bash ~/.config/hypr/scripts/hypr_action full_screenshot
  ;;
restarthyprpanel)
  /bin/bash ~/.config/hypr/scripts/hypr_panel restart
  ;;
clearnotification)
  /bin/bash ~/.config/hypr/scripts/hypr_panel clear-notif
  ;;
lockscreen)
  hyprlock >/dev/null
  ;;
typingtest)
  kitty -o font_size=20 -e smassh
  ;;
esac
