font_family JetBrainsMono Nerd Font
font_features JetBrainsMonoNF-Regular -calt
font_size 10

allow_remote_control socket-only
listen_on unix:/tmp/kitty
shell_integration enabled

# background_opacity 0.8
dynamic_background_opacity true
shell /usr/bin/fish
enable_audio_bell no
placement_strategy top-left

enabled_layouts grid, stack

cursor_trail 1
cursor_blink_interval 0.5 ease-in-out

tab_bar_edge bottom
tab_bar_style custom
tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{index}: {title}"

include keymap.conf
include gruv_material.conf
