# BACKGROUND
background {
    monitor =
    path = ~/.config/background
    blur_passes = 2
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# GENERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
}

# INPUT FIELD
input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(100, 114, 125, 0.5)
    font_color = rgb(200, 200, 200)
    check_color = rgba(125, 174, 163, 0.8)
    fail_color = rgba(234, 105, 98, 0.8)
    fail_text = $FAIL <b>($ATTEMPTS)</b>
    fade_on_empty = false
    font_family = Ubuntu Nerd Font Propo Regular
    placeholder_text = <span foreground="##ffffff99">Hi, $USER</span>
    hide_input = false
    position = 0, -200
    halign = center
    valign = center
}

# Hour-Time
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%H")"
    color = rgba(125, 174, 163, 0.8)
    font_size = 140
    font_family = Ubuntu Nerd Font Propo Bold
 
    position = 0, 240
    halign = center
    valign = center
}

# Minute-Time
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%M")"
    color = rgba(255, 255, 255, .6)
    font_size = 140
    font_family = Ubuntu Nerd Font Propo Bold
    position = 0, 90
    halign = center
    valign = center
}

# Day-Date-Month
label {
    monitor =
    text = cmd[update:1000] echo "<span color='##ffffff99'>$(date '+%A, ')</span><span color='##7DAEA3CC'>$(date '+%d %B')</span>"
    font_size = 14
    font_family = Ubuntu Nerd Font Propo Regular
    position = 0, -20
    halign = center
    valign = center
}

# USER
label {
    monitor =
    text = 
    color = rgba(255, 255, 255, .65)
    font_size = 60
    position = 0, -100
    halign = center
    valign = center
}

