#!/bin/env bash

ss_file_path=~/Pictures/Screenshots/$(date +%Y-%m-%d_%H-%m-%s).jpg

take_full_ss() {
  grim -t jpeg $ss_file_path
  dunstify -u normal -i NONE "Screenshot saved at $ss_file_path"
}

take_rect_ss() {
  grim -g "$(slurp -d)" - | wl-copy
  dunstify -u normal -i NONE "Screenshot copied to clipboard"
}

case $1 in
    full_screenshot)
    take_full_ss
    ;;

    rectangle_screenshot)
    take_rect_ss
    ;;
esac
