#!/usr/bin/env bash

case $1 in
record-gif)
  REC_FILE_PATH=~/Videos/$(date +%Y-%m-%d_%H-%m-%s).gif
  REC_DIR=~/Videos/
  area="$(slurp -d)"

  if [[ -n "$area" ]]; then
    wf-recorder -g "$area" -F fps=30 -c gif -f "$REC_FILE_PATH"
    dunstify -u normal -i NONE "Record" "Saved at $REC_DIR"
  fi
  ;;
esac
