#!/bin/env bash

case $1 in
waybar)
  killall waybar
  pkill waybar
  sleep 0.2
  waybar &
  ;;
dunst)
  killall dunst
  pkill dunst
  sleep 0.2
  dunst &
  ;;
ags)
  killall ags
  pkill ags
  sleep 0.2
  ags &
  ;;
esac
