#!/bin/env bash

case $1 in
  waybar)
    killall waybar
    pkill waybar
    sleep 0.2
    waybar & > /dev/null
    ;;
  dunst)
    killall dunst
    pkill dunst
    sleep 0.2
    dunst & > /dev/null
    ;;
esac
