#!/bin/env bash

case $1 in
waybar)
  killall waybar
  pkill waybar
  sleep 0.2
  waybar &
  ;;
wbar)
  killall -SIGUSR2 waybar
  ;;
dunst)
  killall dunst
  pkill dunst
  sleep 0.2
  dunst &
  ;;
nc)
  swaync-client --reload-config
  ;;
ncss)
  swaync-client --reload-css
  ;;
esac
