#!/usr/bin/env bash

case $1 in
  disable-int)
  sleep 1
  hyprctl keyword monitor eDP-1, disable 
  ;;
  
  enable-int)
  sleep 1
  hyprctl keyword monitor eDP-1, preferred, auto, auto
  ;;
  
  disable-ext)
  sleep 1
  hyprctl keyword monitor HDMI-A-1, disable 
  ;;
  
  enable-ext)
  sleep 1
  hyprctl keyword monitor HDMI-A-1, preferred, auto, auto
  ;;
esac
