#!/bin/env bash

# Create directory if doesn't exist yet
mkdir -p "$HOME/.cache"

# File to store the Bluetooth state
STATE_FILE="$HOME/.cache/bluetooth_state"

# Read the current state from the file
file_state=$(cat "$STATE_FILE")

# Check the Bluetooth state using bluetoothctl
bluetooth_state=$(bluetoothctl show | grep "Powered" | awk '{print $2}')

if [ "$file_state" == "on" ]; then
  if [ "$bluetooth_state" == "no" ]; then
    bluetoothctl power on
    echo "on" >"$STATE_FILE"
  fi
else
  if [ "$bluetooth_state" == "yes" ]; then
    bluetoothctl power off
    echo "off" >"$STATE_FILE"
  fi
fi
