#!/bin/env bash

SS_FILE_PATH=~/Pictures/Screenshots/$(date +%Y-%m-%d_%H-%m-%s).jpg
SS_DIR=~/Pictures/Screenshots/

check_dir_exist() {
  if [ ! -d "$SS_DIR" ]; then
    mkdir -p $SS_DIR
  fi
}

take_full_ss() {
  grimblast --notify --freeze copysave output "$SS_FILE_PATH"
}

take_rect_ss() {
  grimblast --notify --freeze copysave area "$SS_FILE_PATH"
}

take_color_pick() {
  if [[ -n "$(hyprpicker -a)" ]]; then
    notify-send "Color picker" "Color copied to clipboard"
  fi
}

idle_inhibitor_toggle() {
  if pgrep "hypridle" >/dev/null; then
    pkill hypridle
    hyprctl notify 1 3000 red Hypridle Inactive
  else
    hypridle &
    hyprctl notify 1 3000 blue Hypridle Active
  fi
}

toggle_gamemode() {
  HYPRGAMEMODE=$(hyprctl getoption animations:enabled | awk 'NR==1{print $2}')

  if [ "$HYPRGAMEMODE" = 1 ]; then
    hyprctl --batch "\
          keyword animations:enabled 0;\
          keyword decoration:shadow:enabled 0;\
          keyword decoration:blur:enabled 0;\
          keyword general:gaps_in 0;\
          keyword general:gaps_out 0;\
          keyword decoration:rounding 0;"

    hyprctl notify 5 3000 0 "Game mode on"

    exit
  fi

  hyprctl notify -1 3000 0 "Game mode off"
  hyprctl reload
}

case $1 in
full_screenshot)
  check_dir_exist
  take_full_ss
  ;;

rectangle_screenshot)
  check_dir_exist
  take_rect_ss
  ;;

color_pick)
  take_color_pick
  ;;

idle_toggle)
  idle_inhibitor_toggle
  ;;

gamemode)
  toggle_gamemode
  ;;
esac
