#!/bin/env bash

SS_FILE_PATH=~/Pictures/Screenshots/$(date +%Y-%m-%d_%H-%m-%s).jpg
SS_DIR=~/Pictures/Screenshots/

check_dir_exist() {
  if [ ! -d "$SS_DIR" ]; then
    mkdir -p $SS_DIR
  fi
}

take_full_ss() {
  grimblast --notify --freeze copysave output "$SS_FILE_PATH"
}

take_rect_ss() {
  grimblast --notify --freeze copysave area "$SS_FILE_PATH"
}

take_color_pick() {
  if [[ -n "$(hyprpicker -a)" ]]; then
    notify-send "Color picker" "Color copied to clipboard"
  fi
}

toggle_gamemode() {
  HYPRGAMEMODE=$(hyprctl getoption animations:enabled | awk 'NR==1{print $2}')

  if [ "$HYPRGAMEMODE" = 1 ]; then
    hyprctl --batch "\
          keyword animations:enabled 0;\
          keyword decoration:shadow:enabled 0;\
          keyword decoration:blur:enabled 0;" --quiet

    notify-send "Hyprland" "Game mode on"
    exit
  fi

  hyprctl reload --quiet
  notify-send "Hyprland" "Game mode off"
}

toggle_hide_window() {
  ISWINDOWPINNED=$(hyprctl activewindow | grep 'pinned:' | tail -n 1 | awk '{print $2}')

  if [ "$ISWINDOWPINNED" = 1 ]; then
    hyprctl dispatch pin
  fi

  hyprctl --batch "\
        dispatch togglespecialworkspace magic;\
        dispatch movetoworkspace +0;\
        dispatch togglespecialworkspace magic;\
        dispatch movetoworkspace special:magic;\
        dispatch togglespecialworkspace magic;" --quiet
}

case $1 in
full_screenshot)
  check_dir_exist
  take_full_ss
  ;;

rectangle_screenshot)
  check_dir_exist
  take_rect_ss
  ;;

color_pick)
  take_color_pick
  ;;

gamemode)
  toggle_gamemode
  ;;

hide_window)
  toggle_hide_window
  ;;
esac
